# ~/.config/starship.toml
format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$fill\
[ ](fg:#1d2230)\
$nodejs\
$rust\
$golang\
$php\
$cmd_duration\ 
$jobs\
$time\
[ ](fg:#1d2230)\
\n$character"""

[fill]
symbol = " "
# style = "bg:#1d2230"

[jobs]
number_threshold = 1
format = "[$symbol]($style)"


[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
# symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
ignore_branches = ['master', 'main']

#[git_status]
#style = "bg:#394260"
#format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
# symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
# symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
# symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
# symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
# time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'


[battery]
full_symbol = "󰂄"
charging_symbol = "󱊥"
discharging_symbol = "󰁺"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 10  # Show command duration over 10 milliseconds 
format = "[[$duration](bg:#1d2230)]($style)"
style = "bold dimmed white"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[julia]
format = "[$symbol$version]($style) "
symbol = "ஃ "
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[package]
disabled = true

[python]
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'
style = "bold green"
pyenv_version_name = true


[username]
style_user = "bold dimmed blue"
show_always = false

[container]
format = '[$symbol \[$name\]]($style) '
